GET http://localhost:5000/api/v1/user/dsdsds

###
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "email": "admin3@example.com",
    "password": "154446"
}

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin2@example.com",
    "password": "123456"
}

###
GET http://localhost:5000/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJhZG1pbjJAZXhhbXBsZS5jb20iLCJyb2xlX2NvZGUiOiJSMyIsImlhdCI6MTY3NjYyMDAyMSwiZXhwIjoxNjc3MDUyMDIxfQ.gyZw0GdzAIO2zxqm4WSiwIw_Fs-8tnUMM_m-IZSMMBg

###
GET http://localhost:5000/api/v1/insert/

###
GET http://localhost:5000/api/v1/book/
