GET http://localhost:5000/api/v1/user/dsdsds

###
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "email": "admin3@example.com",
    "password": "154446"
}

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin3@example.com",
    "password": "154446"
}

###
GET http://localhost:5000/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbjNAZXhhbXBsZS5jb20iLCJyb2xlX2NvZGUiOiJSMyIsImlhdCI6MTY3ODcwMDM5MywiZXhwIjoxNjc4NzAwMzk4fQ.ObpdipcZalhu0OQ-PhD1Qqtkd-mfZbePn4bRhbfruoQ

###
GET http://localhost:5000/api/v1/insert/

###
GET http://localhost:5000/api/v1/book?id=228ba5e7577e1d49
